### ISSUE TITLE
请在轮播图显示all.json中诗句内容

### ISSUE THREAD

**Issue by skipmaple** [dingguoqing513/custom-swiper#1]
1. API请求 https://v1.jinrishici.com/all.json 内容，使用 { "content": "亭亭山上松，瑟瑟谷中风。" } 来显示滑动的内容

![image](https://github.com/user-attachments/assets/55106c1d-84e9-44f4-bff4-5f5a431e27ff)

Slide3 替换为诗句内容

**Comment by skipmaple** [comment]
<img width="1357" alt="Screenshot 2024-07-18 at 11 18 16" src="https://github.com/user-attachments/assets/152187f6-fbbf-44ca-8827-0fbde655823f">

当前状态只有图

**Comment by dingguoqing513** [comment]
![image](https://github.com/user-attachments/assets/a8ea8ad1-11f7-4199-ae0d-dc697e29a3de)
混合内容:https://*上的页面是通过HTTPS加载的，但是请求了一个不安全的XMLHttpRequest端点http://*.此请求已被阻止;内容必须通过HTTPS提供

github page是https的，您这个是http，已被浏览器作为不安全请求拦截

**Comment by dingguoqing513** [comment]
做个解释：
可以clone下载代码在本地跑一下，另外这个轮播图是简版的（有审题，文字在图片上出不来是因为非法拦截，最后一张不能回到第一张是因为要求中没有说明，所以我这边才加了顶头的限制）
这个轮播图其中很多东西都没有，比如，当前在第几页、快速跳图、在最后一张时很多UI库也设置了是否跳到第一张的选项等等
如果有其他需求，您再告诉我，我去实现~

**Comment by dingguoqing513** [comment]
@skipmaple 已合并部署

**Comment by skipmaple** [comment]
Nice work!
